kumuluzee:
  name: profile
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: profile
    connection-url: jdbc:postgresql://192.168.99.100:5433/profile
    username: postgres
    password: admin
    max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: profile
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: profile-endpoint
      url-pattern: /v1/profile/*
app-properties:
  external-services:
    enabled: true
  healthy: true