kumuluzee:
  name: profile
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: profile
    connection-url: jdbc:postgresql://192.168.99.100:5433/profile
    username: postgres
    password: admin
    max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: profile
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: profile-endpoint
      url-pattern: /v1/profile/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="profile">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="31cf5f91-1968-4614-9342-2bd9b197d6a4-ls.logit.io"
                              port="19821" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'
app-properties:
  external-services:
    enabled: true
  healthy: true